name: jaffle_shop_cloud

profile: jaffle_shop_cloud

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  jaffle_shop_cloud:
    +schema: raw
    raw_orders:
      +column_types:
        ORDERED_AT: timestamp
    raw_stores:
      +column_types:
        opened_at: timestamp

models:
  jaffle_shop_cloud:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
